"""
Configure population_metrics tool for CDCR data.

Creates config_custom.py file that:
1. Maps CDCR data columns to population_metrics expectations
2. Defines violent/nonviolent offense classifications
3. Sets metric weights for suitability scoring

Usage:
    python 01_configure_population_metrics.py                # Interactive mode
    python 01_configure_population_metrics.py --auto         # Auto mode (use defaults)
    python 01_configure_population_metrics.py --source github --auto  # GitHub data
"""

import pandas as pd
from pathlib import Path
import sys
import argparse


def load_selection_criteria(source='local', data_dir='../data'):
    """Load offense tables from selection_criteria.xlsx"""
    if source == 'github':
        print("Loading selection criteria from GitHub...")
        url = "https://raw.githubusercontent.com/redoio/offenses_data/main/selection_criteria.xlsx"
        try:
            df = pd.read_excel(url, sheet_name='Penal codes')
            print(f"✓ Loaded {len(df)} offense codes from GitHub")
            return df
        except Exception as e:
            print(f"⚠️  Could not load from GitHub: {e}")
            source = 'local'
    
    if source == 'local':
        try:
            path = Path(data_dir) / "selection_criteria.xlsx"
            df = pd.read_excel(path, sheet_name='Penal codes')
            print(f"✓ Loaded {len(df)} offense codes from local file")
            return df
        except FileNotFoundError:
            print(f"⚠️  selection_criteria.xlsx not found in {data_dir}")
            return None


def auto_generate_offense_lists(selection_df):
    """Generate violent/nonviolent lists from selection_criteria"""
    print("\n" + "="*70)
    print("AUTO-GENERATING OFFENSE LISTS")
    print("="*70)
    
    # Table B = Violent felonies
    violent = selection_df[selection_df['Table'] == 'Table B']['Offenses'].tolist()
    
    # Table A (not in B) = Serious but nonviolent
    table_a = selection_df[selection_df['Table'] == 'Table A']['Offenses'].tolist()
    nonviolent = [code for code in table_a if code not in violent]
    
    # Clean
    violent = [str(c).strip() for c in violent if pd.notna(c)]
    nonviolent = [str(c).strip() for c in nonviolent if pd.notna(c)]
    
    print(f"\n✓ Violent codes (Table B): {len(violent)} offenses")
    print(f"  Sample: {violent[:5]}")
    print(f"\n✓ Nonviolent codes (Table A, not in B): {len(nonviolent)} offenses")
    print(f"  Sample: {nonviolent[:5]}")
    
    return violent, nonviolent


def create_config_file(violent_codes, nonviolent_codes, source='local', 
                       external_dir='../external_repos/population_metrics'):
    """Generate config_custom.py for population_metrics"""
    
    # Data paths
    if source == 'github':
        paths = {
            'demographics': "https://raw.githubusercontent.com/redoio/resentencing_data_initiative/main/data/demographics.csv",
            'current_commitments': "https://raw.githubusercontent.com/redoio/resentencing_data_initiative/main/data/current_commitments.csv",
            'prior_commitments': "https://raw.githubusercontent.com/redoio/resentencing_data_initiative/main/data/prior_commitments.csv"
        }
        cfg_profile = "PROD"
    else:
        paths = {
            'demographics': "../../data/demographics.csv",
            'current_commitments': "../../data/current_commitments.csv",
            'prior_commitments': "../../data/prior_commitments.csv"
        }
        cfg_profile = "DEV"
    
    config_content = f'''"""
Custom configuration for population_metrics
Auto-generated by 01_configure_population_metrics.py
"""

CFG_PROFILE = "{cfg_profile}"

PATHS = {{
    "demographics": "{paths['demographics']}",
    "current_commitments": "{paths['current_commitments']}",
    "prior_commitments": "{paths['prior_commitments']}"
}}

COLS = {{
    'id': 'cdcno',
    'current_sentence_months': 'aggregate sentence in months',
    'offense_begin_date': 'offense begin date',
    'release_date': 'expected release date',
    'offense_code': 'offense',
    'offense_description': 'offense description',
    'offense_category': 'offense category',
    'in_prison': 'in prison',
    'age_years': None,
    'completed_months': None,
    'past_time_months': None
}}

OFFENSE_LISTS = {{
    'violent': {violent_codes},
    'nonviolent': {nonviolent_codes}
}}

DEFAULTS = {{
    'months_elapsed_total': None,
    'freq_min_rate': 0.0,
    'freq_max_rate': 0.05,
    'age_min': 18,
    'age_max': 90,
    'require_time_fields': False
}}

METRIC_WEIGHTS = {{
    'desc_nonvio_curr': +1.0,
    'desc_nonvio_past': +1.0,
    'severity_trend': +1.0,
    'age': -0.5,
    'freq_violent': -1.0,
    'freq_total': -0.5
}}
'''
    
    config_path = Path(external_dir) / "config_custom.py"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print("\n" + "="*70)
    print("✓ CONFIG FILE CREATED")
    print("="*70)
    print(f"Location: {config_path}")
    print(f"Data source: {'GitHub URLs' if source == 'github' else 'Local files'}")
    
    return config_path


def main():
    parser = argparse.ArgumentParser(description='Configure population_metrics')
    parser.add_argument('--source', choices=['local', 'github'], default='local')
    parser.add_argument('--data-dir', default='../data')
    parser.add_argument('--external-dir', default='../external_repos/population_metrics')
    parser.add_argument('--auto', action='store_true', help='Non-interactive mode')
    
    args = parser.parse_args()
    
    print("="*70)
    print("POPULATION METRICS CONFIGURATION")
    print("="*70)
    
    # Load selection criteria
    selection_df = load_selection_criteria(args.source, args.data_dir)
    
    if selection_df is None:
        print("\n✗ ERROR: Cannot proceed without selection_criteria.xlsx")
        sys.exit(1)
    
    # Generate offense lists
    violent, nonviolent = auto_generate_offense_lists(selection_df)
    
    if not violent and not nonviolent:
        print("\n✗ ERROR: No offense codes generated")
        sys.exit(1)
    
    # Create config
    create_config_file(violent, nonviolent, args.source, args.external_dir)
    
    print("\n" + "="*70)
    print("✓ CONFIGURATION COMPLETE")
    print("="*70)
    print("\nNext steps:")
    print(f"1. cd {args.external_dir}")
    print("2. python run.py --out ../../outputs/population_metrics.csv")
    print("3. Check: outputs/population_metrics.csv")


if __name__ == "__main__":
    main()
